server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wangwei?characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: wangwei
    password: wangwei

logging:
  level:
    org: DEBUG
      
zuul:
  routes:  
    uaa:
      path: /uaa/**
      url: http://127.0.0.1:9999/uaa/
    account:
      path: /account/**
      sensitiveHeaders: 
      serviceId: account-service
      
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#security:
#  user:
#    name: root
#    password: password
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8765/uua/oauth/token
#      userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:8765/uaa/user
#      preferTokenInfo: false  
#  sessions: ALWAYS 
    
security:
  oauth2:
    sso:
      loginPath: /uaa/login      
    client:
      accessTokenUri: http://127.0.0.1:9999/uua/oauth/token
      userAuthorizationUri: http://127.0.0.1:9999/uua/oauth/authorize
      clientId: acme
      clientSecret: secret
      clientAuthenticationScheme: form   
    resource:
      userInfoUri: http://127.0.0.1:9999/user
      preferTokenInfo: false  
  sessions: ALWAYS 